# Generated by Django 4.2.7 on 2023-12-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumno_email_profesor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
